version: '3'
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db.sqlite3:/usr/src/api_service/db.sqlite3
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
