# Generated by Django 3.1.7 on 2022-11-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=100)),
                ('area_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tla', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('competition', models.ManyToManyField(to='api.Competition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('nationality', models.CharField(max_length=30)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
