# Generated by Django 3.1.7 on 2022-11-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221112_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tla',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
